import keyMirror from 'keymirror';

export default keyMirror({
    AUTHORIZE_SUCCESS: null,
    AUTHORIZE_FAIL: null,
    LOGOUT_SUCCESS: null,
    GETTASKLISTS_SUCCESS: null,
    GETTASKLISTS_FAIL: null,
    CREATE_NEW_TASK_SUCCESS: null,
    CREATE_NEW_TASK_FAIL: null,
    GET_TASKS_SUCCESS: null,
    GET_TASKS_FAIL: null,
    UPDATE_TASK_SUCCESS: null,
    UPDATE_TASK_FAIL: null,
    CREATE_TASK_SUCCESS: null,
    CREATE_TASK_FAIL: null,
    UPDATE_TASK_TITLE_SUCCESS: null,
    UPDATE_TASK_TITLE_FAIL: null,
    DELETE_TASK_SUCCESS: null,
    DELETE_TASK_FAIL: null,
    GET_TASK_LIST_TITLE_SUCCESS: null,
    GET_TASK_LIST_TITLE_FAIL: null,
    UPDATE_TASK_LIST_TITLE_SUCCESS: null,
    UPDATE_TASK_LIST_TITLE_FAIL: null,
    DELETE_TASK_LIST_SUCCESS: null,
    DELETE_TASK_LIST_FAIL: null
})